/**
 * Copyright (C) 2026 Percona LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  // Exports used only inside their own module are live; the `export` keyword is merely unnecessary.
  ignoreExportsUsedInFile: true,
  // Generated by openapi-typescript; unused `webhooks` / `$defs` types are emitted unconditionally.
  ignore: ['packages/*/src/generated/**'],
  workspaces: {
    'packages/shell': {
      // Peer dependency of @pmm-extensions/framework, which the shell must provide.
      ignoreDependencies: ['@melloware/react-logviewer'],
    },
    'packages/apps/alters': {
      // Needed by the package's JSX to type-check; knip cannot see the implicit use.
      ignoreDependencies: ['@types/react'],
    },
    'packages/api': {
      // Run by the `codegen` script, not imported.
      ignoreDependencies: ['openapi-typescript'],
    },
  },
};

export default config;
