import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  // Exports used only inside their own module are live; the `export` keyword is merely unnecessary.
  ignoreExportsUsedInFile: true,
  // Generated by openapi-typescript; unused `webhooks` / `$defs` types are emitted unconditionally.
  ignore: ['packages/*/src/generated/**'],
  workspaces: {
    'packages/shell': {
      // Peer dependency of @pmm-extensions/framework, which the shell must provide.
      ignoreDependencies: ['@melloware/react-logviewer'],
    },
    'packages/apps/alters': {
      // Needed by the package's JSX to type-check; knip cannot see the implicit use.
      ignoreDependencies: ['@types/react'],
    },
    'packages/api': {
      // Run by the `codegen` script, not imported.
      ignoreDependencies: ['openapi-typescript'],
    },
  },
};

export default config;
